// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdSi0FrVtyWM4dbYEkAOjeBkLrg90kBd0',
    appId: '1:48438413136:web:f7bfae1d15b5fbb5d3ce55',
    messagingSenderId: '48438413136',
    projectId: 'travel-sharing-app-12b05',
    authDomain: 'travel-sharing-app-12b05.firebaseapp.com',
    storageBucket: 'travel-sharing-app-12b05.firebasestorage.app',
    measurementId: 'G-F68V673W42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtjpKrosAoVhZo1MdTmEnkThoU25No6OA',
    appId: '1:48438413136:android:aed297159ac84b28d3ce55',
    messagingSenderId: '48438413136',
    projectId: 'travel-sharing-app-12b05',
    storageBucket: 'travel-sharing-app-12b05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcTgQ5aRJ7onKxJ3brrWYnoCfS1fVXzwY',
    appId: '1:48438413136:ios:b13fab8ed7fa18edd3ce55',
    messagingSenderId: '48438413136',
    projectId: 'travel-sharing-app-12b05',
    storageBucket: 'travel-sharing-app-12b05.firebasestorage.app',
    iosBundleId: 'com.example.travelSharingApp',
  );
}
