// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUMGfUero73EDuYdUUDpwY24a-Nc936YA',
    appId: '1:978476159167:web:da1d05d4ff96e9c9ff760a',
    messagingSenderId: '978476159167',
    projectId: 'travel-sharing-app-42b85',
    authDomain: 'travel-sharing-app-42b85.firebaseapp.com',
    storageBucket: 'travel-sharing-app-42b85.firebasestorage.app',
    measurementId: 'G-RF08HGFCWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1r5kC-hKkyuhvY1gGruB3niIbqA53WF8',
    appId: '1:978476159167:android:8cbb70db7fc88656ff760a',
    messagingSenderId: '978476159167',
    projectId: 'travel-sharing-app-42b85',
    storageBucket: 'travel-sharing-app-42b85.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJtzVhuIywDrBQOafbHQiDCAEMcawjNkk',
    appId: '1:978476159167:ios:6002c5594514b8efff760a',
    messagingSenderId: '978476159167',
    projectId: 'travel-sharing-app-42b85',
    storageBucket: 'travel-sharing-app-42b85.firebasestorage.app',
    iosBundleId: 'com.example.travelSharingApp',
  );
}
